services:
  app:
    image: fwb-task-list-app:latest
    env_file:
      - ../.env

  nginx:
    image: fwb-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/ssl:/etc/ssl