services:
  app:
    image: gvbusa/{{ APP }}:{{ VERSION }}
    env_file:
      - .env

  nginx:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./ssl:/etc/ssl